export const ACCESS_FEATURES = {
  // Visual & Screen Access
  screen_reader: "Screen-reader friendly",
  accessible_application: "Accessible website/application",
  keyboard_friendly: "Keyboard-friendly application",
  assistive_tech: "Assistive technology support",

  // Hearing Support
  sign_interpreter: "Sign-language interpreter / video interview",
  captions_first: "Captions-first meetings",
  captioned_meetings: "Captioned meetings",
  text_communication: "Text-based communication",
  chat_interviews: "Chat-based interviews",

  // Mobility & Physical Access
  step_free_access: "Step-free workplace access",
  accessible_washrooms: "Accessible washrooms",
  accessible_transport: "Accessible parking / transport nearby",
  accessible_workplace: "Accessible workplace",
  remote_hybrid_option: "Remote or hybrid options",

  // Cognitive & Neurodivergent Support
  plain_language: "Plain-language job descriptions",
  clear_interview_formats: "Clear interview formats shared in advance",
  quiet_workspace: "Quiet workspace",
  written_instructions: "Written instructions",
  extended_time_assessments: "Extended time for assessments",

  // Invisible & Chronic Conditions Support
  flexible_hours: "Flexible hours",
  remote_days: "Remote days",
  rest_breaks: "Rest breaks",
  leave_flexibility: "Leave flexibility",
  flexible_work: "Flexible work",
  remote_work: "Remote work",
  accessible_interview: "Accessible interview process",
} as const;

export type DisabilityCategory = "vision" | "hearing" | "mobility" | "neurodivergent" | "chronic";

export const ACCESS_CATEGORIES: {
  id: DisabilityCategory;
  name: string;
  description: string;
  features: (keyof typeof ACCESS_FEATURES)[];
}[] = [
  {
    id: "vision",
    name: "Visual & Screen Access",
    description: "Support for blind, low-vision, and screen-reader users",
    features: ["screen_reader", "accessible_application", "keyboard_friendly", "assistive_tech"],
  },
  {
    id: "hearing",
    name: "Hearing & Deaf Support",
    description: "Captions, sign language interpreters, and text-first communication",
    features: [
      "sign_interpreter",
      "captions_first",
      "captioned_meetings",
      "text_communication",
      "chat_interviews",
    ],
  },
  {
    id: "mobility",
    name: "Mobility & Physical Access",
    description: "Step-free facilities, accessible washrooms, and transport",
    features: [
      "step_free_access",
      "accessible_washrooms",
      "accessible_transport",
      "accessible_workplace",
      "remote_hybrid_option",
    ],
  },
  {
    id: "neurodivergent",
    name: "Cognitive & Neurodivergent",
    description: "Clear formats, plain language, quiet spaces, and extended time",
    features: [
      "plain_language",
      "clear_interview_formats",
      "quiet_workspace",
      "written_instructions",
      "extended_time_assessments",
    ],
  },
  {
    id: "chronic",
    name: "Invisible & Chronic Conditions",
    description: "Flexible hours, rest breaks, remote days, and adaptable leave",
    features: [
      "flexible_hours",
      "remote_days",
      "rest_breaks",
      "leave_flexibility",
      "flexible_work",
      "remote_work",
      "accessible_interview",
    ],
  },
];

export const INCLUSION_FEATURES = {
  lgbtq_policy: "LGBTQ+ inclusive policy",
  gender_neutral_facilities: "Gender-neutral facilities",
  equal_opportunity: "Equal opportunity policy",
  inclusive_hiring: "Inclusive hiring program",
} as const;

export type AccessFeature = keyof typeof ACCESS_FEATURES;
export type InclusionFeature = keyof typeof INCLUSION_FEATURES;
export type WorkMode = "Remote" | "Hybrid" | "On-site";
export type Employment = "Full-time" | "Part-time" | "Internship" | "Contract";
export type ExperienceBand = "Fresher" | "0-2 years" | "2-5 years" | "5+ years";
export type Category =
  | "Software"
  | "Data"
  | "Design"
  | "Customer Support"
  | "HR"
  | "Marketing"
  | "Content"
  | "Finance"
  | "Operations";

export type Job = {
  id: string;
  title: string;
  company: string;
  city: string;
  workMode: WorkMode;
  employment: Employment;
  experience: ExperienceBand;
  category: Category;
  salary?: string | undefined;
  posted: string;
  about: string;
  responsibilities: string[];
  requiredSkills: string[];
  preferredSkills: string[];
  access: AccessFeature[];
  inclusion: InclusionFeature[];
  /** Source of the accessibility information shown on this listing. */
  accessSource:
    "Provided by employer" | "Verified by AccessPath" | "Discovered via TinyFish Web Search";
  /** True when the employer added accessibility information after posting. */
  accessUpdated?: boolean;
  /** Where this job came from: static seed data or employer-posted via server. */
  source?: "static" | "employer";
  /** Employer-posted jobs link back to the poster. */
  employerId?: string;
  /** Employer-posted jobs have a publication status. */
  jobStatus?: "draft" | "published" | "closed";
};

export type EmployerJobInput = {
  id: string;
  employerId: string;
  title: string;
  company: string;
  description: string;
  location?: string | undefined;
  workMode: WorkMode;
  employmentType: Employment;
  experienceLevel: ExperienceBand;
  skills: string[];
  salaryRange?: string | undefined;
  accessibilityFeatures?:
    | {
        key?: string;
        feature?: string;
        status: "verified" | "employer-provided" | "not-specified";
      }[]
    | undefined;
  inclusionFeatures?: InclusionFeature[] | undefined;
  status: "draft" | "published" | "closed";
  createdAt?: string | undefined;
};

export function employerJobToJob(ej: EmployerJobInput): Job {
  const verifiedFeatures: AccessFeature[] = (ej.accessibilityFeatures || [])
    .filter((f) => f.status === "verified" || f.status === "employer-provided")
    .map((f) => (f.key || f.feature || "") as AccessFeature)
    .filter((k): k is AccessFeature => k in ACCESS_FEATURES);

  const hasVerified = (ej.accessibilityFeatures || []).some((f) => f.status === "verified");
  const accessSource: Job["accessSource"] = hasVerified
    ? "Verified by AccessPath"
    : "Provided by employer";

  let posted = "Recently";
  if (ej.createdAt) {
    try {
      const diffMs = Date.now() - new Date(ej.createdAt).getTime();
      const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
      if (diffDays <= 0) posted = "Today";
      else if (diffDays === 1) posted = "1 day ago";
      else posted = `${diffDays} days ago`;
    } catch {
      posted = "Recently";
    }
  }

  return {
    id: ej.id,
    title: ej.title,
    company: ej.company,
    city: ej.location || (ej.workMode === "Remote" ? "Remote" : "Bengaluru"),
    workMode: ej.workMode,
    employment: ej.employmentType,
    experience: ej.experienceLevel,
    category: "Software",
    salary: ej.salaryRange,
    posted,
    about: ej.description,
    responsibilities: [],
    requiredSkills: ej.skills || [],
    preferredSkills: [],
    access: verifiedFeatures,
    inclusion: (ej.inclusionFeatures as InclusionFeature[]) || [],
    accessSource,
    source: "employer",
    employerId: ej.employerId,
    jobStatus: ej.status,
  };
}

type Tuple = [
  string,
  string,
  string,
  string,
  WorkMode,
  Employment,
  ExperienceBand,
  Category,
  string | undefined,
  string,
  string,
  string[],
  string[],
  string[],
  AccessFeature[],
  InclusionFeature[],
  Job["accessSource"],
];

const rows: Tuple[] = [
  [
    "j1",
    "Junior Frontend Developer",
    "TechNova India",
    "Bengaluru",
    "Remote",
    "Full-time",
    "0-2 years",
    "Software",
    "₹5–8 LPA",
    "2 days ago",
    "Build and maintain accessible customer-facing web interfaces for TechNova's SaaS products, working closely with design and QA.",
    [
      "Implement responsive UI components from design specs",
      "Fix accessibility defects reported by QA and users",
      "Write unit tests for shared components",
      "Participate in weekly code reviews",
    ],
    ["React", "JavaScript", "HTML", "CSS"],
    ["TypeScript", "WAI-ARIA", "Jest"],
    ["remote_work", "screen_reader", "flexible_work", "accessible_interview", "keyboard_friendly"],
    ["equal_opportunity", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j2",
    "Backend Engineer (Node.js)",
    "Meridian Systems",
    "Pune",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Software",
    "₹12–18 LPA",
    "4 days ago",
    "Own backend services powering Meridian's logistics platform, from API design to production reliability.",
    [
      "Design and ship REST APIs",
      "Optimise PostgreSQL queries",
      "Own on-call rotation for owned services",
      "Mentor junior engineers",
    ],
    ["Node.js", "PostgreSQL", "REST APIs", "Git"],
    ["AWS", "Redis", "Docker"],
    [
      "accessible_application",
      "keyboard_friendly",
      "flexible_work",
      "captioned_meetings",
      "accessible_workplace",
    ],
    ["equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j3",
    "Data Analyst",
    "Kaveri Analytics",
    "Chennai",
    "Remote",
    "Full-time",
    "0-2 years",
    "Data",
    "₹6–9 LPA",
    "1 day ago",
    "Turn product and marketing data into decisions for Kaveri's retail clients across South India.",
    [
      "Build dashboards and weekly reports",
      "Write SQL for ad-hoc analysis",
      "Present findings to client stakeholders",
      "Maintain data quality checks",
    ],
    ["SQL", "Excel", "Data Visualisation"],
    ["Python", "Power BI", "Statistics"],
    ["remote_work", "screen_reader", "assistive_tech", "accessible_interview"],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j4",
    "Data Analyst (Fresher Program)",
    "Indus Digital Labs",
    "Hyderabad",
    "Hybrid",
    "Full-time",
    "Fresher",
    "Data",
    "₹4.5–6 LPA",
    "6 days ago",
    "A 12-month structured entry program for graduates starting an analytics career.",
    [
      "Complete guided analytics projects",
      "Support senior analysts with data prep",
      "Document dashboards and metrics",
    ],
    ["SQL", "Excel"],
    ["Python", "Tableau"],
    ["accessible_interview", "keyboard_friendly", "flexible_work", "captioned_meetings"],
    ["inclusive_hiring", "equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j5",
    "Senior Data Scientist",
    "Sahyadri AI",
    "Bengaluru",
    "Remote",
    "Full-time",
    "5+ years",
    "Data",
    "₹28–40 LPA",
    "3 days ago",
    "Lead forecasting and pricing models used by Sahyadri's enterprise customers.",
    [
      "Own model lifecycle end to end",
      "Define evaluation methodology",
      "Partner with engineering on deployment",
      "Coach the analytics team",
    ],
    ["Python", "Machine Learning", "SQL", "Statistics"],
    ["MLOps", "PyTorch", "Causal inference"],
    ["remote_work", "flexible_work", "screen_reader", "assistive_tech", "captioned_meetings"],
    ["equal_opportunity", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j6",
    "Customer Support Associate",
    "Nimbus Telecom Services",
    "Coimbatore",
    "Remote",
    "Full-time",
    "Fresher",
    "Customer Support",
    "₹2.8–3.6 LPA",
    "Today",
    "Support Nimbus broadband customers over chat and voice with clear, patient troubleshooting.",
    [
      "Resolve customer queries over chat and calls",
      "Log issues in the CRM",
      "Escalate technical faults",
      "Meet quality and response targets",
    ],
    ["Communication", "English", "Tamil"],
    ["CRM tools", "Hindi"],
    ["remote_work", "screen_reader", "assistive_tech", "accessible_application", "flexible_work"],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j7",
    "Customer Success Executive",
    "BluePeak SaaS",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Customer Support",
    "₹7–10 LPA",
    "5 days ago",
    "Own renewals and adoption for BluePeak's mid-market accounts.",
    [
      "Run onboarding for new accounts",
      "Track product adoption metrics",
      "Drive renewals and upsells",
      "Capture product feedback",
    ],
    ["Account management", "Communication", "SaaS"],
    ["HubSpot", "Data analysis"],
    ["accessible_workplace", "captioned_meetings", "flexible_work", "accessible_interview"],
    ["lgbtq_policy", "gender_neutral_facilities", "equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j8",
    "HR Executive",
    "Anantara Consulting",
    "Delhi",
    "On-site",
    "Full-time",
    "0-2 years",
    "HR",
    "₹4–6 LPA",
    "1 week ago",
    "Support end-to-end recruitment and employee lifecycle operations for a 400-person consulting firm.",
    [
      "Coordinate interviews and offers",
      "Maintain HRMS records",
      "Run onboarding and induction",
      "Support engagement initiatives",
    ],
    ["Recruitment", "MS Office", "Communication"],
    ["HRMS", "Labour law basics"],
    ["accessible_workplace", "accessible_interview", "keyboard_friendly"],
    ["equal_opportunity", "gender_neutral_facilities", "inclusive_hiring"],
    "Provided by employer",
  ],
  [
    "j9",
    "Talent Acquisition Specialist",
    "Vistara Talent Partners",
    "Remote",
    "Remote",
    "Full-time",
    "2-5 years",
    "HR",
    "₹8–12 LPA",
    "3 days ago",
    "Hire technology talent for startups, with a focus on inclusive and bias-aware processes.",
    [
      "Own full-cycle recruitment",
      "Build structured interview kits",
      "Advise hiring managers on inclusive practices",
      "Report on pipeline health",
    ],
    ["Sourcing", "Interviewing", "Stakeholder management"],
    ["Tech hiring", "ATS tools"],
    ["remote_work", "flexible_work", "captioned_meetings", "accessible_interview", "screen_reader"],
    ["inclusive_hiring", "lgbtq_policy", "equal_opportunity"],
    "Verified by AccessPath",
  ],
  [
    "j10",
    "Digital Marketing Executive",
    "Sunhill Media",
    "Ahmedabad",
    "Hybrid",
    "Full-time",
    "0-2 years",
    "Marketing",
    "₹3.6–5.5 LPA",
    "2 days ago",
    "Run paid and organic campaigns for D2C brands.",
    [
      "Manage Google and Meta ad campaigns",
      "Track and report campaign performance",
      "Coordinate creatives with designers",
      "Run keyword research",
    ],
    ["Google Ads", "SEO", "Analytics"],
    ["Meta Ads", "Copywriting"],
    ["accessible_application", "keyboard_friendly", "flexible_work"],
    ["equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j11",
    "Performance Marketing Manager",
    "Orbit Commerce",
    "Gurugram",
    "Hybrid",
    "Full-time",
    "5+ years",
    "Marketing",
    "₹18–26 LPA",
    "5 days ago",
    "Own paid acquisition P&L across channels for a growing e-commerce business.",
    [
      "Own CAC and ROAS targets",
      "Lead a team of three specialists",
      "Plan quarterly channel budgets",
      "Run experimentation roadmap",
    ],
    ["Performance marketing", "Analytics", "Budget ownership"],
    ["Marketing automation", "SQL"],
    ["accessible_workplace", "captioned_meetings", "flexible_work", "accessible_interview"],
    ["equal_opportunity", "lgbtq_policy"],
    "Provided by employer",
  ],
  [
    "j12",
    "Content Writer",
    "Lantern Content Studio",
    "Remote",
    "Remote",
    "Full-time",
    "0-2 years",
    "Content",
    "₹4–6 LPA",
    "Today",
    "Write clear long-form content for fintech and SaaS clients.",
    [
      "Write blogs, guides and landing pages",
      "Research topics and interview experts",
      "Edit and proofread teammates' drafts",
      "Follow SEO briefs",
    ],
    ["Writing", "Editing", "SEO basics"],
    ["Fintech knowledge", "Interviewing"],
    ["remote_work", "screen_reader", "assistive_tech", "flexible_work", "accessible_application"],
    ["equal_opportunity", "lgbtq_policy", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j13",
    "Technical Content Writer",
    "Meridian Systems",
    "Pune",
    "Remote",
    "Contract",
    "2-5 years",
    "Content",
    "₹9–13 LPA",
    "1 week ago",
    "Document APIs and developer workflows for Meridian's platform.",
    [
      "Write and maintain API documentation",
      "Produce integration tutorials",
      "Review release notes with engineers",
    ],
    ["Technical writing", "Markdown", "APIs"],
    ["OpenAPI", "Git"],
    ["remote_work", "keyboard_friendly", "screen_reader", "flexible_work"],
    ["equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j14",
    "UI/UX Designer",
    "Pixelmint Design",
    "Bengaluru",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Design",
    "₹10–15 LPA",
    "4 days ago",
    "Design accessible product experiences for healthcare and education clients.",
    [
      "Own flows from wireframe to handoff",
      "Run usability sessions",
      "Maintain the design system",
      "Pair with engineers on accessibility",
    ],
    ["Figma", "Interaction design", "Design systems"],
    ["WCAG 2.2", "Prototyping", "User research"],
    ["accessible_workplace", "captioned_meetings", "accessible_interview", "flexible_work"],
    ["lgbtq_policy", "gender_neutral_facilities", "equal_opportunity"],
    "Verified by AccessPath",
  ],
  [
    "j15",
    "Accessibility Design Intern",
    "Pixelmint Design",
    "Remote",
    "Remote",
    "Internship",
    "Fresher",
    "Design",
    "₹25,000/month",
    "2 days ago",
    "Six-month internship supporting accessibility audits and inclusive design work.",
    [
      "Support WCAG audits of client products",
      "Prepare annotated design specs",
      "Document findings and fixes",
    ],
    ["Figma", "Attention to detail"],
    ["WCAG basics", "Screen readers"],
    ["remote_work", "screen_reader", "assistive_tech", "accessible_interview", "keyboard_friendly"],
    ["inclusive_hiring", "equal_opportunity", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j16",
    "Accounts Executive",
    "Deccan Finserv",
    "Hyderabad",
    "On-site",
    "Full-time",
    "0-2 years",
    "Finance",
    "₹3.5–5 LPA",
    "6 days ago",
    "Handle daily accounting entries, reconciliations and GST filings.",
    [
      "Maintain books in Tally",
      "Prepare bank reconciliations",
      "Support monthly closing",
      "Assist with GST returns",
    ],
    ["Tally", "Accounting", "Excel"],
    ["GST", "Zoho Books"],
    ["accessible_workplace", "keyboard_friendly", "accessible_interview"],
    ["equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j17",
    "Financial Analyst",
    "Deccan Finserv",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Finance",
    "₹11–16 LPA",
    "3 days ago",
    "Build financial models and business cases for the corporate finance team.",
    [
      "Own the monthly MIS pack",
      "Build three-statement models",
      "Support fundraising diligence",
      "Analyse unit economics",
    ],
    ["Financial modelling", "Excel", "MIS"],
    ["Power BI", "SQL"],
    ["accessible_workplace", "captioned_meetings", "flexible_work", "screen_reader"],
    ["equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j18",
    "Operations Associate",
    "Saffron Logistics",
    "Chennai",
    "On-site",
    "Full-time",
    "Fresher",
    "Operations",
    "₹3–4.2 LPA",
    "5 days ago",
    "Coordinate daily dispatch and delivery operations at the Chennai hub.",
    [
      "Track shipments and exceptions",
      "Coordinate with delivery partners",
      "Maintain daily operations reports",
    ],
    ["Coordination", "Excel", "Communication"],
    ["Tamil", "Logistics software"],
    ["accessible_workplace", "accessible_interview", "assistive_tech"],
    ["equal_opportunity", "inclusive_hiring"],
    "Provided by employer",
  ],
  [
    "j19",
    "Operations Manager",
    "Saffron Logistics",
    "Bengaluru",
    "On-site",
    "Full-time",
    "5+ years",
    "Operations",
    "₹16–22 LPA",
    "1 week ago",
    "Own hub performance, cost and team for South India operations.",
    [
      "Own hub SLAs and cost per shipment",
      "Lead a team of 25",
      "Drive process improvement projects",
      "Own vendor negotiations",
    ],
    ["Operations management", "People leadership", "Analytics"],
    ["Six Sigma", "SQL"],
    ["accessible_workplace", "captioned_meetings", "accessible_interview"],
    ["equal_opportunity", "gender_neutral_facilities", "lgbtq_policy"],
    "Provided by employer",
  ],
  [
    "j20",
    "QA Engineer (Accessibility)",
    "TechNova India",
    "Remote",
    "Remote",
    "Full-time",
    "2-5 years",
    "Software",
    "₹10–14 LPA",
    "Today",
    "Test TechNova products for functional correctness and accessibility conformance.",
    [
      "Run manual and automated accessibility tests",
      "File and triage defects",
      "Own regression suites",
      "Advise teams on WCAG fixes",
    ],
    ["Manual testing", "WCAG 2.2", "Screen readers"],
    ["Playwright", "axe-core", "CI/CD"],
    [
      "remote_work",
      "screen_reader",
      "assistive_tech",
      "keyboard_friendly",
      "flexible_work",
      "accessible_interview",
    ],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j21",
    "Software Developer (Python)",
    "Indus Digital Labs",
    "Hyderabad",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Software",
    "₹14–20 LPA",
    "2 days ago",
    "Build backend services and internal tooling for enterprise clients.",
    [
      "Develop Django services",
      "Integrate third-party APIs",
      "Write automated tests",
      "Support production releases",
    ],
    ["Python", "Django", "SQL"],
    ["Celery", "AWS", "Docker"],
    ["accessible_application", "keyboard_friendly", "captioned_meetings", "flexible_work"],
    ["equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j22",
    "Support Engineer (Voice + Email)",
    "Nimbus Telecom Services",
    "Remote",
    "Remote",
    "Part-time",
    "0-2 years",
    "Customer Support",
    "₹18,000–24,000/month",
    "4 days ago",
    "Part-time technical support role with fixed evening shifts.",
    [
      "Handle tier-1 technical tickets",
      "Document resolutions in the knowledge base",
      "Escalate recurring faults",
    ],
    ["Troubleshooting", "Communication"],
    ["Networking basics", "Hindi"],
    ["remote_work", "flexible_work", "screen_reader", "assistive_tech", "accessible_application"],
    ["inclusive_hiring", "equal_opportunity"],
    "Verified by AccessPath",
  ],
  [
    "j23",
    "HR Operations Intern",
    "Anantara Consulting",
    "Delhi",
    "Hybrid",
    "Internship",
    "Fresher",
    "HR",
    "₹20,000/month",
    "3 days ago",
    "Six-month internship across HR operations and employee experience.",
    ["Maintain employee records", "Support payroll inputs", "Coordinate engagement events"],
    ["MS Office", "Communication"],
    ["HRMS", "Data entry accuracy"],
    ["accessible_workplace", "accessible_interview", "captioned_meetings"],
    ["inclusive_hiring", "gender_neutral_facilities", "equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j24",
    "Social Media Executive",
    "Sunhill Media",
    "Remote",
    "Remote",
    "Full-time",
    "0-2 years",
    "Marketing",
    "₹3.6–5 LPA",
    "6 days ago",
    "Own day-to-day social content and community for three brand accounts.",
    [
      "Plan monthly content calendars",
      "Write captions and briefs",
      "Respond to community comments",
      "Report on engagement",
    ],
    ["Social media", "Copywriting", "Canva"],
    ["Video editing", "Analytics"],
    ["remote_work", "flexible_work", "accessible_application", "screen_reader"],
    ["equal_opportunity", "lgbtq_policy"],
    "Provided by employer",
  ],
  [
    "j25",
    "Business Analyst",
    "BluePeak SaaS",
    "Remote",
    "Remote",
    "Contract",
    "2-5 years",
    "Data",
    "₹12–16 LPA",
    "1 week ago",
    "Bridge product and customer teams with clear requirements and reporting.",
    [
      "Gather and document requirements",
      "Build reporting for leadership",
      "Run process mapping workshops",
    ],
    ["Requirements analysis", "SQL", "Documentation"],
    ["Jira", "Product analytics"],
    ["remote_work", "captioned_meetings", "keyboard_friendly", "flexible_work", "screen_reader"],
    ["equal_opportunity", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j26",
    "Payroll & Compliance Associate",
    "Vistara Talent Partners",
    "Remote",
    "Remote",
    "Full-time",
    "0-2 years",
    "Finance",
    "₹5–7 LPA",
    "2 days ago",
    "Run payroll cycles and statutory compliance for client companies.",
    ["Process monthly payroll", "File PF, ESI and TDS returns", "Resolve employee payroll queries"],
    ["Payroll", "Excel", "Compliance"],
    ["Zoho Payroll", "Labour law"],
    ["remote_work", "screen_reader", "assistive_tech", "flexible_work", "accessible_interview"],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j27",
    "Graphic Designer",
    "Lantern Content Studio",
    "Kolkata",
    "Hybrid",
    "Full-time",
    "0-2 years",
    "Design",
    "₹4–6.5 LPA",
    "5 days ago",
    "Create brand and campaign visuals across digital formats.",
    ["Design social and ad creatives", "Maintain brand templates", "Support pitch decks"],
    ["Figma", "Illustrator", "Typography"],
    ["Motion graphics", "Photoshop"],
    ["accessible_workplace", "flexible_work", "accessible_interview"],
    ["equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j28",
    "Process Associate (Back Office)",
    "Orbit Commerce",
    "Jaipur",
    "On-site",
    "Full-time",
    "Fresher",
    "Operations",
    "₹2.6–3.4 LPA",
    "Today",
    "Handle order verification and back-office data operations.",
    ["Verify and update order data", "Resolve data mismatches", "Meet daily accuracy targets"],
    ["Data entry", "Excel", "Attention to detail"],
    ["Hindi", "CRM tools"],
    ["accessible_workplace", "assistive_tech", "accessible_interview", "keyboard_friendly"],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "tf-mum-1",
    "Accessibility QA & Test Automation Specialist",
    "Acme Technologies (BKC)",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Software",
    "₹9–15 LPA",
    "Discovered via TinyFish",
    "Leading web and digital accessibility audits for enterprise clients in BKC Mumbai. Verify WCAG 2.1 AA conformance using screen readers, automated scanners, and keyboard navigation.",
    [
      "Execute automated accessibility tests using axe-core and Pa11y",
      "Perform screen reader verification with NVDA, JAWS, and VoiceOver",
      "Collaborate with engineering teams to remediate ARIA landmarks and focus management",
      "Document VPAT (Voluntary Product Accessibility Templates)",
    ],
    ["Accessibility Testing", "WCAG 2.1", "Screen Readers", "WAI-ARIA", "JavaScript"],
    ["axe-core", "Cypress", "Python", "Mobile Accessibility"],
    [
      "screen_reader",
      "assistive_tech",
      "accessible_workplace",
      "flexible_work",
      "accessible_interview",
      "keyboard_friendly",
    ],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Discovered via TinyFish Web Search",
  ],
  [
    "tf-mum-2",
    "Senior Frontend UI Engineer (Accessible Systems)",
    "BuiltIn Tech Innovations (Lower Parel)",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Software",
    "₹14–22 LPA",
    "Discovered via TinyFish",
    "Develop customer-facing web applications with first-class keyboard navigation, high contrast mode support, and seamless screen reader UX from Lower Parel Mumbai.",
    [
      "Build modular design system components using React and Tailwind CSS",
      "Ensure all UI components pass strict accessibility checks and WCAG standards",
      "Optimize core web vitals and client-side performance",
      "Mentor developers on accessible front-end architecture",
    ],
    ["React", "TypeScript", "HTML5", "CSS", "WAI-ARIA"],
    ["Next.js", "Design Systems", "Jest", "Tailwind CSS"],
    [
      "keyboard_friendly",
      "accessible_application",
      "remote_work",
      "flexible_work",
      "accessible_workplace",
    ],
    ["equal_opportunity", "gender_neutral_facilities", "inclusive_hiring"],
    "Discovered via TinyFish Web Search",
  ],
  [
    "tf-mum-3",
    "Data & BI Analyst (Accessible Visualizations)",
    "Powai Analytics Group (Hiranandani)",
    "Mumbai",
    "On-site",
    "Full-time",
    "0-2 years",
    "Data",
    "₹6–10 LPA",
    "Discovered via TinyFish",
    "Join our analytics center in Powai Mumbai. Create executive dashboards, automated pipelines, and accessible data reports with color-blind safe palettes and table alternative views.",
    [
      "Build interactive business intelligence dashboards with Power BI and SQL",
      "Implement accessible data visualizations compliant with cognitive and color-vision accessibility guidelines",
      "Cleanse, transform, and model data from transactional systems",
      "Generate monthly operational reports for cross-functional stakeholders",
    ],
    ["SQL", "Power BI", "Excel", "Data Analysis", "Python"],
    ["Tableau", "DAX", "Accessible Charting", "Statistics"],
    ["accessible_workplace", "flexible_work", "assistive_tech", "captioned_meetings"],
    ["equal_opportunity", "inclusive_hiring"],
    "Discovered via TinyFish Web Search",
  ],
  [
    "tf-mum-4",
    "Customer Support Specialist (Inclusion Program)",
    "Tata Tele Services (Vikhroli)",
    "Mumbai",
    "Remote",
    "Full-time",
    "Fresher",
    "Customer Support",
    "₹3.5–5.5 LPA",
    "Discovered via TinyFish",
    "Provide responsive omnichannel support to Pan-India enterprise customers. Dedicated disability-inclusive hiring track with full remote-readiness and assistive workplace tooling.",
    [
      "Handle inbound customer inquiries via email, live chat, and support ticketing",
      "Resolve account setup, billing, and technical usage queries with high customer satisfaction",
      "Document issue resolution in CRM knowledge base",
      "Collaborate with Tier 2 support teams on incident resolution",
    ],
    ["Customer Support", "Communication", "CRM Tools", "Problem Solving"],
    ["Zendesk", "Live Chat", "Email Etiquette"],
    [
      "remote_work",
      "flexible_work",
      "captioned_meetings",
      "accessible_interview",
      "assistive_tech",
    ],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities"],
    "Discovered via TinyFish Web Search",
  ],
  [
    "tf-mum-5",
    "Quality Auditing Senior Analyst (Accessibility)",
    "Global Tech Hub (Andheri East - SEEPZ)",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "5+ years",
    "Operations",
    "₹15–24 LPA",
    "Discovered via TinyFish",
    "Oversee corporate accessibility governance and compliance standards across global web portals from SEEPZ Andheri East Mumbai.",
    [
      "Lead cross-functional digital accessibility audits for enterprise portals",
      "Establish guidelines for Section 508, EN 301 549, and Indian Rights of Persons with Disabilities (RPwD) standards",
      "Conduct accessibility audits of third-party vendor software before procurement",
      "Train internal development and design teams on universal design principles",
    ],
    ["Accessibility Compliance", "WCAG 2.1", "Quality Auditing", "Risk Management"],
    ["Section 508", "VPAT", "Team Leadership", "ARIA"],
    ["accessible_workplace", "assistive_tech", "flexible_work", "accessible_interview"],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Discovered via TinyFish Web Search",
  ],
];

export const JOBS: Job[] = rows.map((r) => ({
  id: r[0],
  title: r[1],
  company: r[2],
  city: r[3] === "Remote" ? "Remote (India)" : r[3],
  workMode: r[4],
  employment: r[5],
  experience: r[6],
  category: r[7],
  salary: r[8],
  posted: r[9],
  about: r[10],
  responsibilities: r[11],
  requiredSkills: r[12],
  preferredSkills: r[13],
  access: r[14],
  inclusion: r[15],
  accessSource: r[16],
}));

export const CITIES = Array.from(new Set(JOBS.map((j) => j.city))).sort();

export function getJob(id: string) {
  return JOBS.find((j) => j.id === id);
}
