export const ACCESS_FEATURES = {
  // Visual & Screen Access
  screen_reader: "Screen-reader friendly",
  accessible_application: "Accessible website/application",
  keyboard_friendly: "Keyboard-friendly application",
  assistive_tech: "Assistive technology support",

  // Hearing Support
  sign_interpreter: "Sign-language interpreter / video interview",
  captions_first: "Captions-first meetings",
  captioned_meetings: "Captioned meetings",
  text_communication: "Text-based communication",
  chat_interviews: "Chat-based interviews",

  // Mobility & Physical Access
  step_free_access: "Step-free workplace access",
  accessible_washrooms: "Accessible washrooms",
  accessible_transport: "Accessible parking / transport nearby",
  accessible_workplace: "Accessible workplace",
  remote_hybrid_option: "Remote or hybrid options",

  // Cognitive & Neurodivergent Support
  plain_language: "Plain-language job descriptions",
  clear_interview_formats: "Clear interview formats shared in advance",
  quiet_workspace: "Quiet workspace",
  written_instructions: "Written instructions",
  extended_time_assessments: "Extended time for assessments",

  // Invisible & Chronic Conditions Support
  flexible_hours: "Flexible hours",
  remote_days: "Remote days",
  rest_breaks: "Rest breaks",
  leave_flexibility: "Leave flexibility",
  flexible_work: "Flexible work",
  remote_work: "Remote work",
  accessible_interview: "Accessible interview process",
} as const;

export type DisabilityCategory = "vision" | "hearing" | "mobility" | "neurodivergent" | "chronic";

export const ACCESS_CATEGORIES: {
  id: DisabilityCategory;
  name: string;
  description: string;
  features: (keyof typeof ACCESS_FEATURES)[];
}[] = [
  {
    id: "vision",
    name: "Visual & Screen Access",
    description: "Support for blind, low-vision, and screen-reader users",
    features: ["screen_reader", "accessible_application", "keyboard_friendly", "assistive_tech"],
  },
  {
    id: "hearing",
    name: "Hearing & Deaf Support",
    description: "Captions, sign language interpreters, and text-first communication",
    features: [
      "sign_interpreter",
      "captions_first",
      "captioned_meetings",
      "text_communication",
      "chat_interviews",
    ],
  },
  {
    id: "mobility",
    name: "Mobility & Physical Access",
    description: "Step-free facilities, accessible washrooms, and transport",
    features: [
      "step_free_access",
      "accessible_washrooms",
      "accessible_transport",
      "accessible_workplace",
      "remote_hybrid_option",
    ],
  },
  {
    id: "neurodivergent",
    name: "Cognitive & Neurodivergent",
    description: "Clear formats, plain language, quiet spaces, and extended time",
    features: [
      "plain_language",
      "clear_interview_formats",
      "quiet_workspace",
      "written_instructions",
      "extended_time_assessments",
    ],
  },
  {
    id: "chronic",
    name: "Invisible & Chronic Conditions",
    description: "Flexible hours, rest breaks, remote days, and adaptable leave",
    features: [
      "flexible_hours",
      "remote_days",
      "rest_breaks",
      "leave_flexibility",
      "flexible_work",
      "remote_work",
      "accessible_interview",
    ],
  },
];

export const INCLUSION_FEATURES = {
  lgbtq_policy: "LGBTQ+ inclusive policy",
  gender_neutral_facilities: "Gender-neutral facilities",
  equal_opportunity: "Equal opportunity policy",
  inclusive_hiring: "Inclusive hiring program",
} as const;

export type AccessFeature = keyof typeof ACCESS_FEATURES;
export type InclusionFeature = keyof typeof INCLUSION_FEATURES;
export type WorkMode = "Remote" | "Hybrid" | "On-site";
export type Employment = "Full-time" | "Part-time" | "Internship" | "Contract";
export type ExperienceBand = "Fresher" | "0-2 years" | "2-5 years" | "5+ years";
export type Category =
  | "Software"
  | "Data"
  | "Design"
  | "Customer Support"
  | "HR"
  | "Marketing"
  | "Content"
  | "Finance"
  | "Operations";

export type Job = {
  id: string;
  title: string;
  company: string;
  city: string;
  workMode: WorkMode;
  employment: Employment;
  experience: ExperienceBand;
  category: Category;
  salary?: string | undefined;
  posted: string;
  about: string;
  description?: string;
  transparencyLevel?: "verified" | "employer" | "unspecified";
  responsibilities: string[];
  requiredSkills: string[];
  preferredSkills: string[];
  access: AccessFeature[];
  inclusion: InclusionFeature[];
  /** Source of the accessibility information shown on this listing. */
  accessSource:
    "Provided by employer" | "Verified by AccessPath" | "Discovered via TinyFish Web Search";
  /** True when the employer added accessibility information after posting. */
  accessUpdated?: boolean;
  /** Where this job came from: static seed data or employer-posted via server. */
  source?: "static" | "employer";
  /** Employer-posted jobs link back to the poster. */
  employerId?: string;
  /** Employer-posted jobs have a publication status. */
  jobStatus?: "draft" | "published" | "closed";
};

export type EmployerJobInput = {
  id: string;
  employerId: string;
  title: string;
  company: string;
  description: string;
  location?: string | undefined;
  workMode: WorkMode;
  employmentType: Employment;
  experienceLevel: ExperienceBand;
  skills: string[];
  salaryRange?: string | undefined;
  accessibilityFeatures?:
    | {
        key?: string;
        feature?: string;
        status: "verified" | "employer-provided" | "not-specified";
      }[]
    | undefined;
  inclusionFeatures?: InclusionFeature[] | undefined;
  status: "draft" | "published" | "closed";
  createdAt?: string | undefined;
};

export function employerJobToJob(ej: EmployerJobInput): Job {
  const verifiedFeatures: AccessFeature[] = (ej.accessibilityFeatures || [])
    .filter((f) => f.status === "verified" || f.status === "employer-provided")
    .map((f) => (f.key || f.feature || "") as AccessFeature)
    .filter((k): k is AccessFeature => k in ACCESS_FEATURES);

  const hasVerified = (ej.accessibilityFeatures || []).some((f) => f.status === "verified");
  const accessSource: Job["accessSource"] = hasVerified
    ? "Verified by AccessPath"
    : "Provided by employer";

  let posted = "Recently";
  if (ej.createdAt) {
    try {
      const diffMs = Date.now() - new Date(ej.createdAt).getTime();
      const diffDays = Math.floor(diffMs / (1000 * 60 * 60 * 24));
      if (diffDays <= 0) posted = "Today";
      else if (diffDays === 1) posted = "1 day ago";
      else posted = `${diffDays} days ago`;
    } catch {
      posted = "Recently";
    }
  }

  return {
    id: ej.id,
    title: ej.title,
    company: ej.company,
    city: ej.location || (ej.workMode === "Remote" ? "Remote" : "Bengaluru"),
    workMode: ej.workMode,
    employment: ej.employmentType,
    experience: ej.experienceLevel,
    category: "Software",
    salary: ej.salaryRange,
    posted,
    about: ej.description,
    responsibilities: [],
    requiredSkills: ej.skills || [],
    preferredSkills: [],
    access: verifiedFeatures,
    inclusion: (ej.inclusionFeatures as InclusionFeature[]) || [],
    accessSource,
    source: "employer",
    employerId: ej.employerId,
    jobStatus: ej.status,
  };
}

type Tuple = [
  string,
  string,
  string,
  string,
  WorkMode,
  Employment,
  ExperienceBand,
  Category,
  string | undefined,
  string,
  string,
  string[],
  string[],
  string[],
  AccessFeature[],
  InclusionFeature[],
  Job["accessSource"],
];

const rows: Tuple[] = [
  [
    "j1",
    "Junior Frontend Developer",
    "TechNova India",
    "Bengaluru",
    "Remote",
    "Full-time",
    "0-2 years",
    "Software",
    "₹5–8 LPA",
    "2 days ago",
    "Build and maintain accessible customer-facing web interfaces for TechNova's SaaS products, working closely with design and QA.",
    [
      "Implement responsive UI components from design specs",
      "Fix accessibility defects reported by QA and users",
      "Write unit tests for shared components",
      "Participate in weekly code reviews",
    ],
    ["React", "JavaScript", "HTML", "CSS"],
    ["TypeScript", "WAI-ARIA", "Jest"],
    ["remote_work", "screen_reader", "flexible_work", "accessible_interview", "keyboard_friendly"],
    ["equal_opportunity", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j2",
    "Backend Engineer (Node.js)",
    "Meridian Systems",
    "Pune",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Software",
    "₹12–18 LPA",
    "4 days ago",
    "Own backend services powering Meridian's logistics platform, from API design to production reliability.",
    [
      "Design and ship REST APIs",
      "Optimise PostgreSQL queries",
      "Own on-call rotation for owned services",
      "Mentor junior engineers",
    ],
    ["Node.js", "PostgreSQL", "REST APIs", "Git"],
    ["AWS", "Redis", "Docker"],
    [
      "accessible_application",
      "keyboard_friendly",
      "flexible_work",
      "captioned_meetings",
      "accessible_workplace",
    ],
    ["equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j3",
    "Data Analyst",
    "Kaveri Analytics",
    "Chennai",
    "Remote",
    "Full-time",
    "0-2 years",
    "Data",
    "₹6–9 LPA",
    "1 day ago",
    "Turn product and marketing data into decisions for Kaveri's retail clients across South India.",
    [
      "Build dashboards and weekly reports",
      "Write SQL for ad-hoc analysis",
      "Present findings to client stakeholders",
      "Maintain data quality checks",
    ],
    ["SQL", "Excel", "Data Visualisation"],
    ["Python", "Power BI", "Statistics"],
    ["remote_work", "screen_reader", "assistive_tech", "accessible_interview"],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j4",
    "Data Analyst (Fresher Program)",
    "Indus Digital Labs",
    "Hyderabad",
    "Hybrid",
    "Full-time",
    "Fresher",
    "Data",
    "₹4.5–6 LPA",
    "6 days ago",
    "A 12-month structured entry program for graduates starting an analytics career.",
    [
      "Complete guided analytics projects",
      "Support senior analysts with data prep",
      "Document dashboards and metrics",
    ],
    ["SQL", "Excel"],
    ["Python", "Tableau"],
    ["accessible_interview", "keyboard_friendly", "flexible_work", "captioned_meetings"],
    ["inclusive_hiring", "equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j5",
    "Senior Data Scientist",
    "Sahyadri AI",
    "Bengaluru",
    "Remote",
    "Full-time",
    "5+ years",
    "Data",
    "₹28–40 LPA",
    "3 days ago",
    "Lead forecasting and pricing models used by Sahyadri's enterprise customers.",
    [
      "Own model lifecycle end to end",
      "Define evaluation methodology",
      "Partner with engineering on deployment",
      "Coach the analytics team",
    ],
    ["Python", "Machine Learning", "SQL", "Statistics"],
    ["MLOps", "PyTorch", "Causal inference"],
    ["remote_work", "flexible_work", "screen_reader", "assistive_tech", "captioned_meetings"],
    ["equal_opportunity", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j6",
    "Customer Support Associate",
    "Nimbus Telecom Services",
    "Coimbatore",
    "Remote",
    "Full-time",
    "Fresher",
    "Customer Support",
    "₹2.8–3.6 LPA",
    "Today",
    "Support Nimbus broadband customers over chat and voice with clear, patient troubleshooting.",
    [
      "Resolve customer queries over chat and calls",
      "Log issues in the CRM",
      "Escalate technical faults",
      "Meet quality and response targets",
    ],
    ["Communication", "English", "Tamil"],
    ["CRM tools", "Hindi"],
    ["remote_work", "screen_reader", "assistive_tech", "accessible_application", "flexible_work"],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j7",
    "Customer Success Executive",
    "BluePeak SaaS",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Customer Support",
    "₹7–10 LPA",
    "5 days ago",
    "Own renewals and adoption for BluePeak's mid-market accounts.",
    [
      "Run onboarding for new accounts",
      "Track product adoption metrics",
      "Drive renewals and upsells",
      "Capture product feedback",
    ],
    ["Account management", "Communication", "SaaS"],
    ["HubSpot", "Data analysis"],
    ["accessible_workplace", "captioned_meetings", "flexible_work", "accessible_interview"],
    ["lgbtq_policy", "gender_neutral_facilities", "equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j8",
    "HR Executive",
    "Anantara Consulting",
    "Delhi",
    "On-site",
    "Full-time",
    "0-2 years",
    "HR",
    "₹4–6 LPA",
    "1 week ago",
    "Support end-to-end recruitment and employee lifecycle operations for a 400-person consulting firm.",
    [
      "Coordinate interviews and offers",
      "Maintain HRMS records",
      "Run onboarding and induction",
      "Support engagement initiatives",
    ],
    ["Recruitment", "MS Office", "Communication"],
    ["HRMS", "Labour law basics"],
    ["accessible_workplace", "accessible_interview", "keyboard_friendly"],
    ["equal_opportunity", "gender_neutral_facilities", "inclusive_hiring"],
    "Provided by employer",
  ],
  [
    "j9",
    "Talent Acquisition Specialist",
    "Vistara Talent Partners",
    "Remote",
    "Remote",
    "Full-time",
    "2-5 years",
    "HR",
    "₹8–12 LPA",
    "3 days ago",
    "Hire technology talent for startups, with a focus on inclusive and bias-aware processes.",
    [
      "Own full-cycle recruitment",
      "Build structured interview kits",
      "Advise hiring managers on inclusive practices",
      "Report on pipeline health",
    ],
    ["Sourcing", "Interviewing", "Stakeholder management"],
    ["Tech hiring", "ATS tools"],
    ["remote_work", "flexible_work", "captioned_meetings", "accessible_interview", "screen_reader"],
    ["inclusive_hiring", "lgbtq_policy", "equal_opportunity"],
    "Verified by AccessPath",
  ],
  [
    "j10",
    "Digital Marketing Executive",
    "Sunhill Media",
    "Ahmedabad",
    "Hybrid",
    "Full-time",
    "0-2 years",
    "Marketing",
    "₹3.6–5.5 LPA",
    "2 days ago",
    "Run paid and organic campaigns for D2C brands.",
    [
      "Manage Google and Meta ad campaigns",
      "Track and report campaign performance",
      "Coordinate creatives with designers",
      "Run keyword research",
    ],
    ["Google Ads", "SEO", "Analytics"],
    ["Meta Ads", "Copywriting"],
    ["accessible_application", "keyboard_friendly", "flexible_work"],
    ["equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j11",
    "Performance Marketing Manager",
    "Orbit Commerce",
    "Gurugram",
    "Hybrid",
    "Full-time",
    "5+ years",
    "Marketing",
    "₹18–26 LPA",
    "5 days ago",
    "Own paid acquisition P&L across channels for a growing e-commerce business.",
    [
      "Own CAC and ROAS targets",
      "Lead a team of three specialists",
      "Plan quarterly channel budgets",
      "Run experimentation roadmap",
    ],
    ["Performance marketing", "Analytics", "Budget ownership"],
    ["Marketing automation", "SQL"],
    ["accessible_workplace", "captioned_meetings", "flexible_work", "accessible_interview"],
    ["equal_opportunity", "lgbtq_policy"],
    "Provided by employer",
  ],
  [
    "j12",
    "Content Writer",
    "Lantern Content Studio",
    "Remote",
    "Remote",
    "Full-time",
    "0-2 years",
    "Content",
    "₹4–6 LPA",
    "Today",
    "Write clear long-form content for fintech and SaaS clients.",
    [
      "Write blogs, guides and landing pages",
      "Research topics and interview experts",
      "Edit and proofread teammates' drafts",
      "Follow SEO briefs",
    ],
    ["Writing", "Editing", "SEO basics"],
    ["Fintech knowledge", "Interviewing"],
    ["remote_work", "screen_reader", "assistive_tech", "flexible_work", "accessible_application"],
    ["equal_opportunity", "lgbtq_policy", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j13",
    "Technical Content Writer",
    "Meridian Systems",
    "Pune",
    "Remote",
    "Contract",
    "2-5 years",
    "Content",
    "₹9–13 LPA",
    "1 week ago",
    "Document APIs and developer workflows for Meridian's platform.",
    [
      "Write and maintain API documentation",
      "Produce integration tutorials",
      "Review release notes with engineers",
    ],
    ["Technical writing", "Markdown", "APIs"],
    ["OpenAPI", "Git"],
    ["remote_work", "keyboard_friendly", "screen_reader", "flexible_work"],
    ["equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j14",
    "UI/UX Designer",
    "Pixelmint Design",
    "Bengaluru",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Design",
    "₹10–15 LPA",
    "4 days ago",
    "Design accessible product experiences for healthcare and education clients.",
    [
      "Own flows from wireframe to handoff",
      "Run usability sessions",
      "Maintain the design system",
      "Pair with engineers on accessibility",
    ],
    ["Figma", "Interaction design", "Design systems"],
    ["WCAG 2.2", "Prototyping", "User research"],
    ["accessible_workplace", "captioned_meetings", "accessible_interview", "flexible_work"],
    ["lgbtq_policy", "gender_neutral_facilities", "equal_opportunity"],
    "Verified by AccessPath",
  ],
  [
    "j15",
    "Accessibility Design Intern",
    "Pixelmint Design",
    "Remote",
    "Remote",
    "Internship",
    "Fresher",
    "Design",
    "₹25,000/month",
    "2 days ago",
    "Six-month internship supporting accessibility audits and inclusive design work.",
    [
      "Support WCAG audits of client products",
      "Prepare annotated design specs",
      "Document findings and fixes",
    ],
    ["Figma", "Attention to detail"],
    ["WCAG basics", "Screen readers"],
    ["remote_work", "screen_reader", "assistive_tech", "accessible_interview", "keyboard_friendly"],
    ["inclusive_hiring", "equal_opportunity", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j16",
    "Accounts Executive",
    "Deccan Finserv",
    "Hyderabad",
    "On-site",
    "Full-time",
    "0-2 years",
    "Finance",
    "₹3.5–5 LPA",
    "6 days ago",
    "Handle daily accounting entries, reconciliations and GST filings.",
    [
      "Maintain books in Tally",
      "Prepare bank reconciliations",
      "Support monthly closing",
      "Assist with GST returns",
    ],
    ["Tally", "Accounting", "Excel"],
    ["GST", "Zoho Books"],
    ["accessible_workplace", "keyboard_friendly", "accessible_interview"],
    ["equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j17",
    "Financial Analyst",
    "Deccan Finserv",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Finance",
    "₹11–16 LPA",
    "3 days ago",
    "Build financial models and business cases for the corporate finance team.",
    [
      "Own the monthly MIS pack",
      "Build three-statement models",
      "Support fundraising diligence",
      "Analyse unit economics",
    ],
    ["Financial modelling", "Excel", "MIS"],
    ["Power BI", "SQL"],
    ["accessible_workplace", "captioned_meetings", "flexible_work", "screen_reader"],
    ["equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j18",
    "Operations Associate",
    "Saffron Logistics",
    "Chennai",
    "On-site",
    "Full-time",
    "Fresher",
    "Operations",
    "₹3–4.2 LPA",
    "5 days ago",
    "Coordinate daily dispatch and delivery operations at the Chennai hub.",
    [
      "Track shipments and exceptions",
      "Coordinate with delivery partners",
      "Maintain daily operations reports",
    ],
    ["Coordination", "Excel", "Communication"],
    ["Tamil", "Logistics software"],
    ["accessible_workplace", "accessible_interview", "assistive_tech"],
    ["equal_opportunity", "inclusive_hiring"],
    "Provided by employer",
  ],
  [
    "j19",
    "Operations Manager",
    "Saffron Logistics",
    "Bengaluru",
    "On-site",
    "Full-time",
    "5+ years",
    "Operations",
    "₹16–22 LPA",
    "1 week ago",
    "Own hub performance, cost and team for South India operations.",
    [
      "Own hub SLAs and cost per shipment",
      "Lead a team of 25",
      "Drive process improvement projects",
      "Own vendor negotiations",
    ],
    ["Operations management", "People leadership", "Analytics"],
    ["Six Sigma", "SQL"],
    ["accessible_workplace", "captioned_meetings", "accessible_interview"],
    ["equal_opportunity", "gender_neutral_facilities", "lgbtq_policy"],
    "Provided by employer",
  ],
  [
    "j20",
    "QA Engineer (Accessibility)",
    "TechNova India",
    "Remote",
    "Remote",
    "Full-time",
    "2-5 years",
    "Software",
    "₹10–14 LPA",
    "Today",
    "Test TechNova products for functional correctness and accessibility conformance.",
    [
      "Run manual and automated accessibility tests",
      "File and triage defects",
      "Own regression suites",
      "Advise teams on WCAG fixes",
    ],
    ["Manual testing", "WCAG 2.2", "Screen readers"],
    ["Playwright", "axe-core", "CI/CD"],
    [
      "remote_work",
      "screen_reader",
      "assistive_tech",
      "keyboard_friendly",
      "flexible_work",
      "accessible_interview",
    ],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j21",
    "Software Developer (Python)",
    "Indus Digital Labs",
    "Hyderabad",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Software",
    "₹14–20 LPA",
    "2 days ago",
    "Build backend services and internal tooling for enterprise clients.",
    [
      "Develop Django services",
      "Integrate third-party APIs",
      "Write automated tests",
      "Support production releases",
    ],
    ["Python", "Django", "SQL"],
    ["Celery", "AWS", "Docker"],
    ["accessible_application", "keyboard_friendly", "captioned_meetings", "flexible_work"],
    ["equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j22",
    "Support Engineer (Voice + Email)",
    "Nimbus Telecom Services",
    "Remote",
    "Remote",
    "Part-time",
    "0-2 years",
    "Customer Support",
    "₹18,000–24,000/month",
    "4 days ago",
    "Part-time technical support role with fixed evening shifts.",
    [
      "Handle tier-1 technical tickets",
      "Document resolutions in the knowledge base",
      "Escalate recurring faults",
    ],
    ["Troubleshooting", "Communication"],
    ["Networking basics", "Hindi"],
    ["remote_work", "flexible_work", "screen_reader", "assistive_tech", "accessible_application"],
    ["inclusive_hiring", "equal_opportunity"],
    "Verified by AccessPath",
  ],
  [
    "j23",
    "HR Operations Intern",
    "Anantara Consulting",
    "Delhi",
    "Hybrid",
    "Internship",
    "Fresher",
    "HR",
    "₹20,000/month",
    "3 days ago",
    "Six-month internship across HR operations and employee experience.",
    ["Maintain employee records", "Support payroll inputs", "Coordinate engagement events"],
    ["MS Office", "Communication"],
    ["HRMS", "Data entry accuracy"],
    ["accessible_workplace", "accessible_interview", "captioned_meetings"],
    ["inclusive_hiring", "gender_neutral_facilities", "equal_opportunity"],
    "Provided by employer",
  ],
  [
    "j24",
    "Social Media Executive",
    "Sunhill Media",
    "Remote",
    "Remote",
    "Full-time",
    "0-2 years",
    "Marketing",
    "₹3.6–5 LPA",
    "6 days ago",
    "Own day-to-day social content and community for three brand accounts.",
    [
      "Plan monthly content calendars",
      "Write captions and briefs",
      "Respond to community comments",
      "Report on engagement",
    ],
    ["Social media", "Copywriting", "Canva"],
    ["Video editing", "Analytics"],
    ["remote_work", "flexible_work", "accessible_application", "screen_reader"],
    ["equal_opportunity", "lgbtq_policy"],
    "Provided by employer",
  ],
  [
    "j25",
    "Business Analyst",
    "BluePeak SaaS",
    "Remote",
    "Remote",
    "Contract",
    "2-5 years",
    "Data",
    "₹12–16 LPA",
    "1 week ago",
    "Bridge product and customer teams with clear requirements and reporting.",
    [
      "Gather and document requirements",
      "Build reporting for leadership",
      "Run process mapping workshops",
    ],
    ["Requirements analysis", "SQL", "Documentation"],
    ["Jira", "Product analytics"],
    ["remote_work", "captioned_meetings", "keyboard_friendly", "flexible_work", "screen_reader"],
    ["equal_opportunity", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j26",
    "Payroll & Compliance Associate",
    "Vistara Talent Partners",
    "Remote",
    "Remote",
    "Full-time",
    "0-2 years",
    "Finance",
    "₹5–7 LPA",
    "2 days ago",
    "Run payroll cycles and statutory compliance for client companies.",
    ["Process monthly payroll", "File PF, ESI and TDS returns", "Resolve employee payroll queries"],
    ["Payroll", "Excel", "Compliance"],
    ["Zoho Payroll", "Labour law"],
    ["remote_work", "screen_reader", "assistive_tech", "flexible_work", "accessible_interview"],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j27",
    "Graphic Designer",
    "Lantern Content Studio",
    "Kolkata",
    "Hybrid",
    "Full-time",
    "0-2 years",
    "Design",
    "₹4–6.5 LPA",
    "5 days ago",
    "Create brand and campaign visuals across digital formats.",
    ["Design social and ad creatives", "Maintain brand templates", "Support pitch decks"],
    ["Figma", "Illustrator", "Typography"],
    ["Motion graphics", "Photoshop"],
    ["accessible_workplace", "flexible_work", "accessible_interview"],
    ["equal_opportunity", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j28",
    "Process Associate (Back Office)",
    "Orbit Commerce",
    "Jaipur",
    "On-site",
    "Full-time",
    "Fresher",
    "Operations",
    "₹2.6–3.4 LPA",
    "Today",
    "Handle order verification and back-office data operations.",
    ["Verify and update order data", "Resolve data mismatches", "Meet daily accuracy targets"],
    ["Data entry", "Excel", "Attention to detail"],
    ["Hindi", "CRM tools"],
    ["accessible_workplace", "assistive_tech", "accessible_interview", "keyboard_friendly"],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "tf-mum-1",
    "Accessibility QA & Test Automation Specialist",
    "Acme Technologies (BKC)",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Software",
    "₹9–15 LPA",
    "Discovered via TinyFish",
    "Leading web and digital accessibility audits for enterprise clients in BKC Mumbai. Verify WCAG 2.1 AA conformance using screen readers, automated scanners, and keyboard navigation.",
    [
      "Execute automated accessibility tests using axe-core and Pa11y",
      "Perform screen reader verification with NVDA, JAWS, and VoiceOver",
      "Collaborate with engineering teams to remediate ARIA landmarks and focus management",
      "Document VPAT (Voluntary Product Accessibility Templates)",
    ],
    ["Accessibility Testing", "WCAG 2.1", "Screen Readers", "WAI-ARIA", "JavaScript"],
    ["axe-core", "Cypress", "Python", "Mobile Accessibility"],
    [
      "screen_reader",
      "assistive_tech",
      "accessible_workplace",
      "flexible_work",
      "accessible_interview",
      "keyboard_friendly",
    ],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Discovered via TinyFish Web Search",
  ],
  [
    "tf-mum-2",
    "Senior Frontend UI Engineer (Accessible Systems)",
    "BuiltIn Tech Innovations (Lower Parel)",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Software",
    "₹14–22 LPA",
    "Discovered via TinyFish",
    "Develop customer-facing web applications with first-class keyboard navigation, high contrast mode support, and seamless screen reader UX from Lower Parel Mumbai.",
    [
      "Build modular design system components using React and Tailwind CSS",
      "Ensure all UI components pass strict accessibility checks and WCAG standards",
      "Optimize core web vitals and client-side performance",
      "Mentor developers on accessible front-end architecture",
    ],
    ["React", "TypeScript", "HTML5", "CSS", "WAI-ARIA"],
    ["Next.js", "Design Systems", "Jest", "Tailwind CSS"],
    [
      "keyboard_friendly",
      "accessible_application",
      "remote_work",
      "flexible_work",
      "accessible_workplace",
    ],
    ["equal_opportunity", "gender_neutral_facilities", "inclusive_hiring"],
    "Discovered via TinyFish Web Search",
  ],
  [
    "tf-mum-3",
    "Data & BI Analyst (Accessible Visualizations)",
    "Powai Analytics Group (Hiranandani)",
    "Mumbai",
    "On-site",
    "Full-time",
    "0-2 years",
    "Data",
    "₹6–10 LPA",
    "Discovered via TinyFish",
    "Join our analytics center in Powai Mumbai. Create executive dashboards, automated pipelines, and accessible data reports with color-blind safe palettes and table alternative views.",
    [
      "Build interactive business intelligence dashboards with Power BI and SQL",
      "Implement accessible data visualizations compliant with cognitive and color-vision accessibility guidelines",
      "Cleanse, transform, and model data from transactional systems",
      "Generate monthly operational reports for cross-functional stakeholders",
    ],
    ["SQL", "Power BI", "Excel", "Data Analysis", "Python"],
    ["Tableau", "DAX", "Accessible Charting", "Statistics"],
    ["accessible_workplace", "flexible_work", "assistive_tech", "captioned_meetings"],
    ["equal_opportunity", "inclusive_hiring"],
    "Discovered via TinyFish Web Search",
  ],
  [
    "tf-mum-4",
    "Customer Support Specialist (Inclusion Program)",
    "Tata Tele Services (Vikhroli)",
    "Mumbai",
    "Remote",
    "Full-time",
    "Fresher",
    "Customer Support",
    "₹3.5–5.5 LPA",
    "Discovered via TinyFish",
    "Provide responsive omnichannel support to Pan-India enterprise customers. Dedicated disability-inclusive hiring track with full remote-readiness and assistive workplace tooling.",
    [
      "Handle inbound customer inquiries via email, live chat, and support ticketing",
      "Resolve account setup, billing, and technical usage queries with high customer satisfaction",
      "Document issue resolution in CRM knowledge base",
      "Collaborate with Tier 2 support teams on incident resolution",
    ],
    ["Customer Support", "Communication", "CRM Tools", "Problem Solving"],
    ["Zendesk", "Live Chat", "Email Etiquette"],
    [
      "remote_work",
      "flexible_work",
      "captioned_meetings",
      "accessible_interview",
      "assistive_tech",
    ],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities"],
    "Discovered via TinyFish Web Search",
  ],
  [
    "tf-mum-5",
    "Quality Auditing Senior Analyst (Accessibility)",
    "Global Tech Hub (Andheri East - SEEPZ)",
    "Mumbai",
    "Hybrid",
    "Full-time",
    "5+ years",
    "Operations",
    "₹15–24 LPA",
    "Discovered via TinyFish",
    "Oversee corporate accessibility governance and compliance standards across global web portals from SEEPZ Andheri East Mumbai.",
    [
      "Lead cross-functional digital accessibility audits for enterprise portals",
      "Establish guidelines for Section 508, EN 301 549, and Indian Rights of Persons with Disabilities (RPwD) standards",
      "Conduct accessibility audits of third-party vendor software before procurement",
      "Train internal development and design teams on universal design principles",
    ],
    ["Accessibility Compliance", "WCAG 2.1", "Quality Auditing", "Risk Management"],
    ["Section 508", "VPAT", "Team Leadership", "ARIA"],
    ["accessible_workplace", "assistive_tech", "flexible_work", "accessible_interview"],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Discovered via TinyFish Web Search",
  ],
  [
    "j29",
    "Digital Accessibility QA Specialist (Screen Reader Focus)",
    "InclusionTech Labs",
    "Bengaluru",
    "Remote",
    "Full-time",
    "0-2 years",
    "Software",
    "₹6–9.5 LPA",
    "1 day ago",
    "Test enterprise SaaS applications using JAWS, NVDA, VoiceOver, and keyboard navigation. Work with frontend engineers to remediate accessibility defects according to WCAG 2.2 AA standards.",
    [
      "Execute functional and manual assistive technology tests on web and mobile workflows",
      "Log detailed accessibility defect tickets with exact DOM locations and suggested ARIA fixes",
      "Collaborate with engineering teams during sprint planning to ensure accessible component architecture",
      "Participate in user-testing sessions with screen-reader users and PwD focus groups",
    ],
    ["Screen Readers (NVDA/JAWS)", "WCAG 2.1 / 2.2", "WAI-ARIA", "HTML5 Semantics", "Manual Testing"],
    ["Axe-core", "Lighthouse", "JavaScript", "VoiceOver iOS/macOS", "Issue Tracking (Jira)"],
    [
      "screen_reader",
      "assistive_tech",
      "keyboard_friendly",
      "accessible_application",
      "remote_work",
      "flexible_hours",
      "accessible_interview",
    ],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j30",
    "Bilingual Community Support Specialist (Indian Sign Language)",
    "SignWave Communications",
    "Delhi",
    "Remote",
    "Full-time",
    "Fresher",
    "Customer Support",
    "₹4–6 LPA",
    "Just now",
    "Provide dedicated customer and community support via Indian Sign Language (ISL) video relay and live text-based chat. Ideal for deaf, hard-of-hearing, or fluent bilingual communicators.",
    [
      "Deliver empathetic customer service via live ISL video sessions and chat tickets",
      "Translate support documentation and FAQs into accessible sign video clips",
      "Coordinate with technical support on customer escalation and bug reporting",
      "Maintain 95%+ first-contact resolution on text-first communication channels",
    ],
    ["Indian Sign Language (ISL)", "Written English / Hindi", "Customer Empathy", "Text Communication", "Ticketing Systems"],
    ["Zendesk", "Video Relay Services", "Knowledge Base Authoring", "Problem Solving"],
    [
      "sign_interpreter",
      "chat_interviews",
      "text_communication",
      "captions_first",
      "captioned_meetings",
      "remote_work",
      "flexible_work",
    ],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities"],
    "Verified by AccessPath",
  ],
  [
    "j31",
    "Inclusive UX/UI Designer (Universal Design Systems)",
    "Ethos Design Studio",
    "Pune",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "Design",
    "₹11–17 LPA",
    "2 days ago",
    "Design intuitive, accessible digital experiences across web and mobile. Build design tokens, high-contrast themes, focus indicators, and cognitive-friendly interfaces in an accessible office.",
    [
      "Architect inclusive design system components in Figma adhering to WCAG 2.2 contrast and touch target guidelines",
      "Design clear mental models, progressive disclosure patterns, and cognitive low-distraction modes",
      "Run participatory design research sessions with disabled candidates and neurodivergent professionals",
      "Provide developers with complete redlines including focus order, accessible names, and ARIA roles",
    ],
    ["Figma", "Design Systems", "WCAG Guidelines", "Interaction Design", "Wireframing"],
    ["Color Contrast Auditing", "Micro-interactions", "HTML/CSS Basics", "User Research"],
    [
      "step_free_access",
      "accessible_washrooms",
      "quiet_workspace",
      "plain_language",
      "accessible_workplace",
      "remote_hybrid_option",
      "assistive_tech",
    ],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j32",
    "Neurodiversity Talent Acquisition Specialist",
    "NeuroCraft Pathways",
    "Hyderabad",
    "Hybrid",
    "Full-time",
    "2-5 years",
    "HR",
    "₹9–15 LPA",
    "3 days ago",
    "Spearhead neuroinclusive hiring programs for top technology employers. Design low-anxiety interview processes, provide advance agendas, and match candidates to inclusive engineering teams.",
    [
      "Design and manage hiring funnels tailored for neurodivergent (ADHD, Autistic, Dyslexic) talent",
      "Provide candidates with transparent interview questions, rubrics, and structural accommodations in advance",
      "Coach hiring managers on reducing sensory stressors, eliminating trick questions, and evaluating skills objectively",
      "Track candidate satisfaction and retention metrics across neuroinclusive cohorts",
    ],
    ["Inclusive Recruiting", "Candidate Experience", "Structured Interviewing", "Stakeholder Coaching", "HR Operations"],
    ["Neurodiversity Advocacy", "RPwD Act Guidelines", "ATS Management", "Employee Relations"],
    [
      "plain_language",
      "clear_interview_formats",
      "quiet_workspace",
      "written_instructions",
      "extended_time_assessments",
      "flexible_work",
      "step_free_access",
    ],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities"],
    "Provided by employer",
  ],
  [
    "j33",
    "Cloud Infrastructure & Reliability Associate (Asynchronous Focus)",
    "Aether Cloud Networks",
    "Chennai",
    "Remote",
    "Full-time",
    "0-2 years",
    "Software",
    "₹7.5–12 LPA",
    "2 days ago",
    "Maintain cloud deployments, CI/CD pipelines, and server health with an asynchronous, documentation-first culture. Structured for individuals managing chronic health conditions or stamina fluctuations.",
    [
      "Manage AWS/GCP cloud services, Docker containers, and automated deployment scripts",
      "Monitor system health metrics, alerting thresholds, and infrastructure logs",
      "Document architectural decisions and incident post-mortems in written asynchronous channels",
      "Automate routine operational tasks using Python and Bash scripting",
    ],
    ["Linux / Unix", "Docker", "Python", "Cloud Fundamentals (AWS/GCP)", "Git"],
    ["Kubernetes", "Terraform", "CI/CD Pipelines", "Prometheus / Grafana"],
    [
      "flexible_hours",
      "remote_days",
      "rest_breaks",
      "leave_flexibility",
      "remote_work",
      "text_communication",
      "accessible_interview",
    ],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j34",
    "Junior Financial Operations & Billing Analyst",
    "Standard Chartered Global Business Services",
    "Bengaluru",
    "On-site",
    "Full-time",
    "Fresher",
    "Finance",
    "₹5–7.5 LPA",
    "4 days ago",
    "Handle financial accounts, invoicing verification, and journal entries. Based in our fully accessible Whitefield technology park featuring step-free access, tactile paving, and dedicated shuttle drop-offs.",
    [
      "Verify client billing statements and match transaction records against purchase orders",
      "Reconcile bank accounts, accounts payable ledgers, and vendor dispute registers",
      "Generate monthly financial variance reports for finance controllers",
      "Ensure compliance with statutory audit checklists and internal accounting controls",
    ],
    ["Financial Accounting", "MS Excel", "Analytical Skills", "Billing Reconciliation", "Basic Tally / ERP"],
    ["SAP FICO", "Financial Reporting", "Data Validation", "Communication"],
    [
      "step_free_access",
      "accessible_washrooms",
      "accessible_transport",
      "accessible_workplace",
      "assistive_tech",
      "accessible_interview",
    ],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities"],
    "Verified by AccessPath",
  ],
  [
    "j35",
    "Accessible Technical Documentation Specialist",
    "DevDoc Systems",
    "Gurugram",
    "Remote",
    "Full-time",
    "0-2 years",
    "Content",
    "₹5.5–8.5 LPA",
    "3 days ago",
    "Write accessible developer documentation, user manuals, and API guides. Emphasize plain language, descriptive text alternatives, and clear visual hierarchies beneficial for all readers.",
    [
      "Author clear, structured markdown guides and tutorial docs for enterprise developers",
      "Ensure all architectural diagrams include rich descriptive alternative text and table fallbacks",
      "Collaborate with software engineers to explain complex concepts in plain, unambiguous language",
      "Maintain documentation readability scores and glossary definitions",
    ],
    ["Technical Writing", "Markdown", "Plain Language Drafting", "Documentation Tools (GitBook/Docusaurus)", "English Fluency"],
    ["Basic Code Understanding (API/JSON)", "Accessibility Standards (Plain English)", "Git", "SEO Basics"],
    [
      "plain_language",
      "written_instructions",
      "flexible_work",
      "remote_work",
      "extended_time_assessments",
      "text_communication",
    ],
    ["equal_opportunity", "inclusive_hiring"],
    "Provided by employer",
  ],
  [
    "j36",
    "Data Annotation & Multimodal AI Safety Reviewer",
    "Turing AI Solutions",
    "Mumbai",
    "Remote",
    "Full-time",
    "Fresher",
    "Data",
    "₹4–6.5 LPA",
    "Just now",
    "Review, classify, and label multimodal datasets for cutting-edge AI models. Highly structured, low-stress daily tasks with quiet, sensory-friendly workflows and text-based supervisor support.",
    [
      "Inspect and label text, image, and tabular dataset samples according to precise guidelines",
      "Identify hallucinations, bias, and quality anomalies in AI model outputs",
      "Log annotation feedback and taxonomy edge cases to data science leads",
      "Meet consistent data quality and accuracy benchmarks at a self-managed, comfortable pace",
    ],
    ["Attention to Detail", "Computer Proficiency", "Basic English Comprehension", "Pattern Recognition", "Data Tagging"],
    ["Basic Python or Spreadsheets", "Annotation Tooling", "Critical Thinking"],
    [
      "quiet_workspace",
      "written_instructions",
      "extended_time_assessments",
      "remote_work",
      "flexible_hours",
      "text_communication",
      "accessible_application",
    ],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities"],
    "Verified by AccessPath",
  ],
  [
    "j37",
    "Digital Content & Social Media Accessibility Producer",
    "BroadReach Media",
    "Bengaluru",
    "Hybrid",
    "Full-time",
    "0-2 years",
    "Marketing",
    "₹5–8 LPA",
    "1 day ago",
    "Produce accessible social campaigns, closed captions, and descriptive media. Ensure all digital marketing collateral is 100% accessible to disabled, deaf, and blind consumers.",
    [
      "Generate accurate, synchronized closed captions and transcripts for podcast and video content",
      "Draft engaging, accessible social posts with descriptive CamelCase hashtags and image alt-text",
      "Audit published digital media for color contrast, readable typography, and screen-reader accessibility",
      "Analyze engagement metrics across inclusive campaigns to optimize audience reach",
    ],
    ["Social Media Management", "Captioning / Subtitling", "Copywriting", "Alt-Text Writing", "Content Strategy"],
    ["Canva / Premiere Basics", "WCAG Color Contrast", "SEO", "Hootsuite / Buffer"],
    [
      "accessible_application",
      "captions_first",
      "text_communication",
      "flexible_hours",
      "remote_hybrid_option",
      "accessible_workplace",
    ],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j38",
    "Senior Accessibility Governance & RPwD Compliance Manager",
    "Wipro Digital Inclusion Office",
    "Bengaluru",
    "Hybrid",
    "Full-time",
    "5+ years",
    "Operations",
    "₹18–28 LPA",
    "5 days ago",
    "Direct corporate accessibility governance, workplace reasonable accommodations, and RPwD Act 2016 statutory compliance across enterprise business units.",
    [
      "Oversee enterprise compliance with Section 21 Equal Opportunity Policies and Section 34 workplace standards",
      "Audit physical infrastructure, assistive technology procurement, and corporate web software",
      "Partner with HR and facilities leaders to establish reasonable accommodation budgets and fast-track fulfillment",
      "Publish annual disability inclusion audits and ESG governance disclosures",
    ],
    ["RPwD Act 2016", "Accessibility Governance", "Corporate Policy", "Workplace Inclusion", "Audit & Risk"],
    ["CPACC / WAS Certification", "VPAT Assessment", "Senior Stakeholder Management", "Legal & Compliance"],
    [
      "accessible_workplace",
      "step_free_access",
      "accessible_washrooms",
      "assistive_tech",
      "remote_hybrid_option",
      "flexible_work",
      "accessible_interview",
    ],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy", "gender_neutral_facilities"],
    "Verified by AccessPath",
  ],
  [
    "j39",
    "Customer Care Associate (100% Chat & Asynchronous Support)",
    "FreshWorks Partner Network",
    "Chennai",
    "Remote",
    "Full-time",
    "Fresher",
    "Customer Support",
    "₹3.5–5 LPA",
    "Just now",
    "Provide text-only live chat and email support for cloud software customers. Zero phone calls or audio communication required, creating an ideal setting for non-verbal or speech-impaired candidates.",
    [
      "Resolve customer billing, login, and product configuration tickets via live chat and email",
      "Maintain fast, friendly, and accurate text replies in alignment with SLA targets",
      "Document frequent questions and contribute clear solutions to the customer knowledge base",
      "Escalate unresolved technical issues to Tier 2 support engineers with clean reproduction notes",
    ],
    ["Written Communication", "Live Chat", "Customer Patience", "Fast Typing Speed", "Basic Troubleshooting"],
    ["Freshdesk / Zendesk", "Knowledge Base Maintenance", "CRM Navigation"],
    [
      "chat_interviews",
      "text_communication",
      "remote_work",
      "flexible_hours",
      "accessible_interview",
      "assistive_tech",
    ],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j40",
    "Assistive Computer Vision & AI Research Intern",
    "AI4Bharat Research Lab",
    "Chennai",
    "Hybrid",
    "Internship",
    "Fresher",
    "Software",
    "₹4–6 LPA (Stipend Equivalent)",
    "2 days ago",
    "Collaborate on open-source Indian Sign Language (ISL) gesture recognition and hands-free assistive webcam models. Work in an accessible research lab equipped with step-free facilities.",
    [
      "Train and benchmark deep learning models for hand landmark tracking and dynamic sign gesture classification",
      "Optimize lightweight models using ONNX and WebAssembly for real-time in-browser inference",
      "Collect and curate inclusive datasets representing diverse skin tones, lighting conditions, and hand geometries",
      "Document experimental results and co-author open-source research tooling",
    ],
    ["Python", "PyTorch / TensorFlow", "Computer Vision Basics", "OpenCV", "Linear Algebra"],
    ["MediaPipe", "ONNX / WebAssembly", "Sign Language Data", "Git", "Model Optimization"],
    [
      "assistive_tech",
      "keyboard_friendly",
      "accessible_application",
      "step_free_access",
      "accessible_workplace",
      "flexible_work",
      "remote_hybrid_option",
    ],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j41",
    "Junior Python & Automation Developer (Neuroinclusive Track)",
    "ThoughtWorks Inclusive Labs",
    "Pune",
    "Remote",
    "Full-time",
    "Fresher",
    "Software",
    "₹6.5–9 LPA",
    "Just now",
    "Develop automation scripts, API integration tests, and data extractors in Python. Features advance interview formats and coding problems provided 48 hours prior to eliminate interview anxiety.",
    [
      "Write clean, maintainable Python scripts for system integration and data processing",
      "Collaborate with senior developers on backend automated testing pipelines",
      "Participate in pair programming sessions with structured, predictable schedules",
      "Document code logic and test cases with clear step-by-step examples",
    ],
    ["Python", "Git", "Problem Solving", "Object-Oriented Programming", "REST APIs"],
    ["pytest", "SQL Basics", "Docker", "Linux Basics"],
    [
      "plain_language",
      "clear_interview_formats",
      "written_instructions",
      "extended_time_assessments",
      "quiet_workspace",
      "remote_work",
      "flexible_hours",
    ],
    ["equal_opportunity", "inclusive_hiring", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j42",
    "Data Quality & Integrity Specialist (Quiet Focus Pods)",
    "Oracle India Innovation Hub",
    "Hyderabad",
    "Hybrid",
    "Full-time",
    "0-2 years",
    "Data",
    "₹7–11 LPA",
    "1 day ago",
    "Perform data schema validation, SQL consistency audits, and ETL monitoring. Located in an accessible campus with dedicated sensory-friendly quiet focus pods and low ambient lighting zones.",
    [
      "Execute automated SQL queries to audit data pipelines for missing or malformed records",
      "Document data discrepancy tickets and track remediation progress",
      "Collaborate asynchronously with database administrators on schema optimizations",
      "Generate weekly data accuracy health cards for reporting dashboards",
    ],
    ["SQL", "Data Validation", "Excel / Spreadsheets", "Analytical Thinking", "Database Concepts"],
    ["Python Basics", "PostgreSQL", "ETL Tools", "Data Quality Frameworks"],
    [
      "quiet_workspace",
      "written_instructions",
      "extended_time_assessments",
      "step_free_access",
      "accessible_workplace",
      "flexible_work",
      "accessible_washrooms",
    ],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities"],
    "Verified by AccessPath",
  ],
  [
    "j43",
    "Digital Accessibility Auditing Associate (WCAG & Assistive Tech)",
    "BarrierBreak Digital",
    "Mumbai",
    "Remote",
    "Full-time",
    "0-2 years",
    "Operations",
    "₹5–8 LPA",
    "2 days ago",
    "Conduct structured accessibility audits across banking, ecommerce, and education portals. Verify compliance with WCAG 2.1 AA and Indian government GIGW standards.",
    [
      "Perform keyboard navigation and screen-reader accessibility evaluations",
      "Evaluate digital content for color contrast, text sizing, and alternative text adequacy",
      "Draft structured audit reports with actionable code remediation snippets",
      "Test digital web forms and document files (PDF/ePub) for accessibility barriers",
    ],
    ["Accessibility Standards (WCAG)", "Screen Reader Testing", "HTML5 Semantics", "Report Writing", "Quality Assurance"],
    ["Axe DevTools", "WAI-ARIA", "Section 508", "PDF Accessibility"],
    [
      "screen_reader",
      "keyboard_friendly",
      "plain_language",
      "written_instructions",
      "assistive_tech",
      "remote_work",
      "flexible_hours",
    ],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j44",
    "Associate People Operations Coordinator (Inclusive Accommodations)",
    "Accenture Inclusion & Diversity Unit",
    "Bengaluru",
    "Hybrid",
    "Full-time",
    "Fresher",
    "HR",
    "₹4.5–6.5 LPA",
    "3 days ago",
    "Coordinate workplace accommodation logistics and onboarding journeys for new PwD hires. Office is located in an audited Bellandur campus with step-free elevators and accessible EV shuttles.",
    [
      "Coordinate assistive technology software and hardware setup for incoming employees",
      "Manage interview accommodation scheduling including sign language interpreters and CART captioners",
      "Maintain confidential accommodation records in accordance with RPwD Act guidelines",
      "Gather post-onboarding feedback to improve workplace accessibility scores",
    ],
    ["Human Resources Basics", "Communication", "Organizational Skills", "Empathy & Discretion", "MS Office"],
    ["RPwD Act Knowledge", "HRIS Software", "Disability Etiquette", "Problem Solving"],
    [
      "plain_language",
      "clear_interview_formats",
      "step_free_access",
      "accessible_washrooms",
      "accessible_transport",
      "accessible_workplace",
      "flexible_work",
    ],
    ["equal_opportunity", "inclusive_hiring", "gender_neutral_facilities", "lgbtq_policy"],
    "Verified by AccessPath",
  ],
  [
    "j45",
    "Front-End Accessibility Engineer (Design Systems)",
    "Swiggy Engineering",
    "Bengaluru",
    "Remote",
    "Full-time",
    "2-5 years",
    "Software",
    "₹16–25 LPA",
    "4 days ago",
    "Engineer core UI design system components with complete ARIA coverage, focus traps, keyboard accessibility, and dyslexia-friendly typography defaults.",
    [
      "Develop accessible React component primitives with robust WAI-ARIA authoring practices",
      "Write automated accessibility tests using Axe-core and Playwright",
      "Review pull requests across consumer-facing web teams for accessibility regressions",
      "Lead developer workshops on building accessible forms, modals, and interactive dropdowns",
    ],
    ["React", "TypeScript", "WAI-ARIA", "WCAG 2.1", "CSS / Tailwind"],
    ["Playwright / Cypress", "Storybook", "Axe-core", "Design Systems"],
    [
      "accessible_application",
      "keyboard_friendly",
      "screen_reader",
      "quiet_workspace",
      "extended_time_assessments",
      "flexible_hours",
      "remote_work",
    ],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
  [
    "j46",
    "Content Research & Fact-Checking Associate (Async Standups)",
    "NextGen Media Labs",
    "Delhi",
    "Remote",
    "Full-time",
    "Fresher",
    "Content",
    "₹3.8–5.5 LPA",
    "Just now",
    "Verify source citations, draft plain-language summaries, and optimize metadata. Designed for high autonomy with asynchronous, written-only daily updates and low sensory stress.",
    [
      "Verify factual accuracy of published articles and informational guides",
      "Draft concise, plain-language summaries of technical and policy documents",
      "Tag digital content with consistent keywords and accessibility alt-text descriptions",
      "Participate in asynchronous text-only team check-ins via Slack / Notion",
    ],
    ["Research Skills", "Written English", "Attention to Detail", "Plain Language", "Fact Checking"],
    ["Content Management Systems (CMS)", "SEO Basics", "Metadata Tagging"],
    [
      "plain_language",
      "written_instructions",
      "quiet_workspace",
      "text_communication",
      "remote_work",
      "rest_breaks",
      "flexible_hours",
    ],
    ["equal_opportunity", "inclusive_hiring"],
    "Verified by AccessPath",
  ],
];

export const JOBS: Job[] = rows.map((r) => ({
  id: r[0],
  title: r[1],
  company: r[2],
  city: r[3] === "Remote" ? "Remote (India)" : r[3],
  workMode: r[4],
  employment: r[5],
  experience: r[6],
  category: r[7],
  salary: r[8],
  posted: r[9],
  about: r[10],
  responsibilities: r[11],
  requiredSkills: r[12],
  preferredSkills: r[13],
  access: r[14],
  inclusion: r[15],
  accessSource: r[16],
}));

export const CITIES = Array.from(new Set(JOBS.map((j) => j.city))).sort();

export function getJob(id: string) {
  return JOBS.find((j) => j.id === id);
}
